version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/woofie-chat
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 22031:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
    networks:
      - woofie-chat-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - woofie-chat-network

  redis:
    container_name: woofie-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - woofie-chat-network

volumes:
  mongodb-data:
  redis-data:

networks:
  woofie-chat-network:
    driver: bridge
